theme: jekyll-theme-slate
title: Pascal’s blog
description: The blog of an IT professional focusing on automation, cloud computing, virtualization.
Tagline: The blog of an IT professional focusing on automation, cloud computing, virtualization.
